### ISSUE TITLE
remove quotes section from front page

### ISSUE THREAD

**Issue by tkimnguyen** [jazkarta/ploneconf2016.policy#4]
We are not going to do quotes... it's going to be too much work and during the conference we will not have time to do this kind of new content generation & updating

**Comment by acsr** [comment]
I removed the quotes for now. But It seems a stupid decision, because we just need 3 quotes minimum as testimonials and personal recommendations of a conference or a product are much more impactful than to bury featuritis in prose looking like a grey lettered desert.
