### ISSUE TITLE
Export the PloneConf2016 Theme from the live theme editor at Plone site "ploneconf_acsrcontent" as zip

### ISSUE THREAD

**Issue by acsr** [jazkarta/ploneconf2016.policy#6]
There is a remaining caching issue (see at the end!).

What I did:
- The existing not active theme "Ploneconf2016" was duplicated before deletion to avoid a name conflict.
- The exported Theme ZIP was imported as "Ploneconf2016" in the live site and activated. It overrides some Barceloneta values but mainly imports it as foundation.
- we added the new main files to manifest.cfg from were you can simply identify the added less files that contain the tweaks.

```
development-css = /++theme++ploneconf2016/less/ploneconf2016.plone.less
production-css = /++theme++ploneconf2016/less/ploneconf2016.plone.css
tinymce-content-css = /++theme++ploneconf2016/less/ploneconf2016.plone.css
```
- On change you need to go to the "ploneconf2016.plone.less" file in the Site Setups Theme Editor and hit [Build CSS] to compile the CSS 
## Caching issue

There is currently a caching issue that makes it impossible for me to check if the changes are propagated. In my development session accessed via the tunnel everything works fine. The Public site takes the content but refuses to propagate the style changes due to too strong caching even after using development mode. I am looking forward for a solution by @tkimnguyen @alecm.

**Comment by acsr** [comment]
I had a broken Theme Editor UI that was related to activation of development mode and Develop CSS in the Resource Registry Setup controlpanel. 

After deactivation of the development mode the Theme Editor Styling was back again.
So we need to manually compile the conference CSS in the theme editor and purge caches.

**Comment by tkimnguyen** [comment]
@acsr I thought when you closed the ticket you no longer had the caching problem, which is resolved by restarting varnish. Please leave the ticket open if you still need help, or please open a new ticket for the specific thing you still need help with.

**Comment by acsr** [comment]
@tkimnguyen absolutely agreed. But the Caching was mentioned just as possible cause of this ticket. Since the issue was caused by misconfigured development mode it was closed for me. That the caching hits back when we leave the logged in area was dicovered later. The caching metioned in this ticket is just a false friend.
